In [31]:
import numpy as np
from sklearn.datasets import load_diabetes
import pandas as pd
np.set_printoptions(suppress=True)

In [40]:
data = load_diabetes()
df = pd.DataFrame(data.data, columns=data.feature_names)

df['diabetes'] = data.target

data = df.values

data.shape

(442, 11)

In [102]:
np.random.seed(42)

multiplier = np.random.randint(low=5)

In [103]:
multiplier

3

In [104]:
np.random.seed(42)

W = np.random.random(size=data.shape[1] - 1) * multiplier

In [105]:
W

array([1.12362036, 2.85214292, 2.19598183, 1.79597545, 0.46805592,
       0.46798356, 0.17425084, 2.59852844, 1.80334504, 2.12421773])

In [106]:
np.random.seed(42)
w_o = np.random.randint(low=5, high=50)

In [107]:
w_o

43

In [108]:
eta = 1

In [110]:
minimum_loss_difference = 0.1

In [111]:
n_iters = 1000

In [144]:
def SGD(data, weights, intercept, n_iters, batch, eta, min_loss):
    """
    Implements the SGD for Linear Regression without Regularization
    
    :param data: datasets -> np.ndarray
    :param weights: The initial weight vector -> np.array
    :param intercept: The initia value of the intercept -> int
    :param batch: The batch size for the stochastic Gradient descend -> int
    :param eta: The learning rate -> float
    :param n_iter: Number of maximum iterations -> int
    :param min_loss: Minimum Loss required to decrease each iteration -> float
    """
    sample_index = np.arange(data.shape[0])
    np.random.shuffle(sample_index)
    sample = data[sample_index[:batch]]
    features = sample[:, 0:-1]
    labels = sample[:, -1]
    for n_iter in range(1, n_iters):
        print(f'Converging for iter {n_iter}')
        
        # Calculate the dW
        
        # Calculate the dw_0
    return features.shape, labels.shape

In [145]:
SGD(data, W, w_o, n_iters, 100, eta, minimum_loss_difference)

((100, 10), (100,))

In [114]:
np.random.randint(low=0, high=1, size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [119]:
a

array([ 70, 236, 218, 250,  39, 171, 157, 110,  72,  86, 233, 348, 174,
       425, 350, 431, 149, 400, 268,  67, 215, 187, 194, 376,  17, 347,
        30, 332, 309, 255, 374, 261, 381, 119, 211,   1,  23, 197, 435,
       213,  63, 123, 373,  14, 206,  88, 291, 361, 333, 260,  47, 355,
       115, 235, 270, 136, 138, 342, 305, 170,  44, 416, 244, 420, 403,
       280, 141, 343, 224, 286, 306,  21, 230, 317, 137,  20, 406, 367,
        60, 130, 225, 175, 103,  66, 325, 107, 139, 303, 315, 302, 297,
       258, 168, 312, 254, 386,  76, 134, 161, 298, 323, 327, 183, 341,
       106, 231,  16, 210, 192, 153, 292, 188,  80, 124, 105, 127, 126,
        87,  96, 287, 120, 387, 129, 414, 209, 281,  78, 208, 198, 300,
       243,  37, 102, 366,  65, 242, 369, 111, 321, 165, 239, 404,  49,
       122, 273, 427, 346,  71, 296, 310,  33,  31, 112, 408,  50, 384,
       109,  77, 318, 207,  82, 409, 423, 434, 227, 368, 382,   5,  54,
       259, 128, 326, 370,  97, 331,  26,  58, 441,  62,  25,  8